### PR TITLE
feat(ui): added login page design figma link and changed the logo

### PR DESCRIPTION
**Pull request by amajaying**

### CODE REVIEW

**Comment by amajaying** [comment]
hey, @kartikvirendrar could you please check into it and let me know so that I can work on the code part? 
Thanks!

**Review by kartikvirendrar — CHANGES_REQUESTED** [review]
resolve conflicts

**Comment by amajaying** [comment]
@kartikvirendrar done brother

**Comment by kartikvirendrar** [comment]
> @kartikvirendrar done brother

still your code has conflicts which must be resolved

**Comment by kartikvirendrar** [comment]
do sync your fork first and then try making changes

**Comment by amajaying** [comment]
please check again, I just resolved all the conflicts. Thanks!

**Review by kartikvirendrar — APPROVED** [review]

**Pull request merged**
