### PR TITLE
fixed alignment of stock cards content

### PR DESCRIPTION
**Pull request by LaLiLuLeLoPS**
Hello I realized this issue not only affects the SBS stock card but could potentially affect any cards with longer than usual names. I have defined dynamic grid column sizes to fix this issue for all cards.

### CODE REVIEW

**Review by kartikvirendrar — CHANGES_REQUESTED** [review]
try doing some more changes, atleast 4-5 lines of code

**Comment by LaLiLuLeLoPS** [comment]
> 
@kartikvirendrar can I add the fix for 32 in this as well then since that is also minor?

**Review by kartikvirendrar — APPROVED** [review]

**Comment by kartikvirendrar** [comment]
> > 
> 
> @kartikvirendrar can I add the fix for 32 in this as well then since that is also minor?

yes you can

**Comment by LaLiLuLeLoPS** [comment]
@kartikvirendrar I merged the other pointer issue code also into this. Hope it is okay now :)

**Comment by LaLiLuLeLoPS** [comment]
Fixed conflicts, ready to merge

**Review by kartikvirendrar — APPROVED** [review]

**Pull request merged**
