### PR TITLE
style: Footer-Style-Changed

### PR DESCRIPTION
**Pull request by gaurav-iitb**

### CODE REVIEW

**Comment by kartikvirendrar** [comment]
do resolve the conflicts and update the PR

**Comment by gaurav-iitb** [comment]
which conflicts you want me to fix

**Comment by kartikvirendrar** [comment]
> which conflicts you want me to fix

do sync your fork once, then make changes to it and update this PR

**Comment by gaurav-iitb** [comment]
I am making another pr and closing this

**Pull request closed without merging**
